apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cdk-shopware-setup
  annotations:
    github.com/project-slug: olandesino/cdk-shopware-setup
spec:
  type: other
  lifecycle: unknown
  owner: olandesino
